### PR TITLE
Fix screenshots

### LINKED ISSUE #523: RecheckWebProperties getInstance() called before init()
## Describe the Bug

`RecheckWebProperties#init()` must be called before `RecheckWebProperties#getInstance()` to ensure that the source `"file:${projectroot}/.retest/retest.properties"` can be resolved. We currently do this in `RecheckSeleniumAdapter#initialize( RecheckOptions )`.

However, the `RecheckWebOptionsBuilder` accesses it before:

```java
@Override
public RecheckWebOptions build() {
	return new RecheckWebOptions( super.build(), checkNamingStrategy, screenshotProvider != null
			? screenshotProvider : RecheckWebProperties.getInstance().screenshotProvider() );
}
```

As a consequence, the `retest.properties` aren't loaded yet. This is also why our own reports for this project contain screenshots, although we set the screenshot provider to `none`.

### How to Reproduce?

```java
// for some test in recheck-web
RecheckWebOptions opts = RecheckWebOptions.builder().build();
System.out.println( opts.getScreenshotProvider() );
// de.retest.web.screenshot.ViewportOnlyMinimalScreenshot@XXXXXXXX
```

Although this is normal usage (create options before a `Recheck` instance) , it will ignore the `retest.properties` and just use the default.

### Setup

- recheck-web: 1.9.0
- Selenium version: 3.141.59
- Testing framework: JUnit5 5.6.0
- OS: macOS 10.15.2
- Java version: OpenJDK 8

### PR DESCRIPTION
**Pull request by beatngu13**
- [x] the code follows the [Clean Code](https://clean-code-developer.com/) guidelines.
- [ ] the necessary tests are either created or updated.
- [ ] all status checks (Travis CI, SonarCloud, etc.) pass.
- [x] your commit history is cleaned up.
- [ ] you updated the changelog.
- [ ] you updated necessary documentation within [retest/docs](https://github.com/retest/docs).

## Description

Fixes #523.

### State of this PR

Any idea for a good test case? Some integration between `RecheckWebOptions` and `RecheckSeleniumAdapter`.

Also, build fails due to #524 and changelog needs to be updated.

### CODE REVIEW

File: src/main/java/de/retest/web/RecheckSeleniumAdapter.java [hunk 1]
```diff
@@ -53,12 +53,17 @@
...
+	}
+
+	private ScreenshotProvider getScreenshotProvider( final RecheckOptions options ) {
 		if ( options instanceof RecheckWebOptions ) {
-			final RecheckWebOptions webOptions = (RecheckWebOptions) options;
-			screenshotProvider = webOptions.getScreenshotProvider();
-		} else {
-			screenshotProvider = RecheckWebProperties.getInstance().screenshotProvider();
+			final ScreenshotProvider fromOptions = ((RecheckWebOptions) options).getScreenshotProvider();
+			if ( fromOptions != null ) {
```
Comment (diba1013) [inline src/main/java/de/retest/web/RecheckSeleniumAdapter.java]: I quite liked the fact that the `RecheckOptionsBuilder` does the check so that the `RecheckOptions` are properly initialized. That was the whole point around the discussion on who should do the initialization: Builder or Options.

This introduces the same problem as with `reportUploadEnabled` which needs the second evaluation for the properties to determine the actual value. Thus it would be the same with the `RecheckOptions`, if moving the report upload to the builder. 

Thus I would suggest to move the init methods within the options, as they are the first to be called. Or maybe into the `RecheckWebProperties#getInstance`?

As a side note. `RecheckOptions#init` and `RecheckWebOptions#init` does the same. As `ConfigFactory` is a static class, wouldn't one of them suffice?

Comment (beatngu13) [reply src/main/java/de/retest/web/RecheckSeleniumAdapter.java]: Will resolve this as discussed in Slack.

**Comment by beatngu13** [comment]
Still can't think of a good integration test … how could we verify that the correct (in our case `none` instead of the default `viewportOnly`) screenshot provider is being used? Check the logs?

**Comment by beatngu13** [comment]
Yep, see:

https://github.com/retest/recheck-web/pull/525#issuecomment-586374521

Any idea?
